### ISSUE TITLE
'tap' events are firing on 'doubletap'

### ISSUE THREAD

**Issue by JohnKis** [taye/interact.js#155]
Hi there,

I'm having a problem with doubletap events. My interactable is listening to both tap and doubletap events but when a doubletap occurs the tap event listener will be called twice and the doubletap event listener once. What I was expecting is that only the doubletap listener will be called. I haven't found a way to achieve that, although I'm might missing something obvious.

**Comment by taye** [comment]
That's also the behaviour of DOM `click` and `dblclick` events so for this and a few other reasons, I think it's better to keep this behaviour. However, you raise a good point: there should be a way to tell if a tap will lead to a double tap so that it can be ignored.

I could add a `double` property to `tap` events to indicate whether a `doubletap` follows so that you could then do something like:

```javascript
interact(target)
  .on('tap', function (event) {
    if (event.double) { return; }

    // code for first tap
  })
  .on('doubletap', function (event) {
    // code for doubletap
  });
```

**Comment by JohnKis** [comment]
Thanks for the quick response. You're right, that's how the DOM click and dblclick work.

As you suggested a 'double' property on the tap event would certainly be useful. If you could add it, that would be great.

**Comment by taye** [comment]
https://rawgit.com/taye/interact.js/master/interact.js

This fix should be available in the next release.
