### ISSUE TITLE
Context option not working for interactables with the same selector

### ISSUE THREAD

**Issue by jordandh** [taye/interact.js#24]
The new context option is not working correctly for interactables that use the same selector. I will use my scenario as an example. I have a list component that is used in multiple places on a page. Within a list you can drag and drop the items to reorder them. The `interact` call for the list component looks like this:

``` javascript
interact('ul > .list-item').context(listElement)...
```

The selector passed to `interact` is the same for each list component on the page. After the first call to `interact` the `interactableGet` function returns the same interactable for the selector `ul > .list-item`. It would seem that a new interactable needs to be made for each selector + context combination.

**Comment by bios21** [comment]
Hi there,

I think I've found a bug with the context option ; if you construct an Interactable object with an HTMLElement instead of CSS selector, the context will be always document.

e.g.
`
interact('*', {context:document.body}) === interact('*', {context: document}); // false [OK]
// but
let test = document.querySelector('#container'); // assuming that we have div#container in DOM
interact(test, {context:document.body}) === interact(test, {context: document}); // true [NOK]
`

Is this really a bug or an expected behavior ?

Thank you :)

**Comment by taye** [comment]
@bios21 I did that intentionally but it's probably better that the specified context is used. It should be a quick change so maybe expect it kind of soonish.

**Comment by taye** [comment]
@bios21. It's done. You can expect it in the next release some time hopefully not too far away.

**Comment by bios21** [comment]
Oh ! Thank you for considering my post !
In my opinion, I think it's a more intuitive behavior.

Great job and keep rockin' !

**Comment by taye** [comment]
@bios21 You're very welcome!
