### ISSUE TITLE
How to convert deprecated snap to new API snap

### ISSUE THREAD

**Issue by HerrimanCoder** [taye/interact.js#240]
I'm trying very hard to convert my deprecated snap approach to the new API snap approach:

Old:
```
.snap({
	mode: 'anchor',
	anchors: [],
	range: Infinity,
	elementOrigin: { x: 0.5, y: 0.2 },
	endOnly: true
})
```

New (boilerplate, from a post):
```
.draggable({
	max: Infinity,
	snap: {
		targets: [
		  { x: 0, y: 0 },                                       
		  interact.createSnapGrid({ x: 25, y: 25 }),            
		  function (x, y) { return { x: x % 50, y: y % 50 }; }
		],
		relativePoints: [ { x: 0.5, y: 0.2 } ]                  
	}
})
```
I am really struggling with this -- the new snap api seems unintuitve. I have read the API docs and still can't figure this out. My "old" version is working perfectly when an element is dropped in an upper dropzone. But when dropped in a lower dropzone, I want the snap behavior a little different. 

One large and immediate problem I have with the new snap code above, is that when I do it that way, my draggable element no longer drags smoothly; it drags choppy, like it's trying to conform to some kind of snap grid. I don't want any snapping behavior until the element reaches a drop zone, but I have no idea what changes I need to make.

taye, in the gitter post I mentioned this problem and you said to switch to the newer API--could you please give me an example of the new snap API that would give me the same behavior as the "old" snap code I posted above? I would greatly appreciate it.

**Comment by taye** [comment]
The problems with the old API are that 

 1. It doesn't support different snap configurations for different actions
 2. The `mode` setting means that you can't easily mix different types of snap targets – you can only have either one grid, one set of "anchor" points or one set of "path" functions/points.
 3. The `elementOrigin` takes only a single object to which snapping can be relative.

With the new API, snapping is set in each action's configuration method separately and all the target types go into a single `targets` array which lets you use any combination of targets. The `elementOrigin` setting which used to be a single object is succeeded by `relativePoints` which is an array of similar objects so that you can snap a relative to a different point on the target element for each `relativePoint` in the array.

To use the new API, instead of passing the snap options object to the `snap` method, remove the `mode` property and put the object in the `<action>able` method options with the property name `snap`. If you had been using "anchor" mode snapping, then to use the new API you should rename the `anchor` property to `targets` and keep the items in the array the same. You should do the same for "path" mode. If you were using "grid" mode then use `interact.createSnapGrid({x,y})` to create a snap function that does grid snapping and put that in the `targets` array.

In your case:

```javascript
.draggable({
  snap: {
    targets: [],  // instead of mode: "anchor" with anchors: []
    range: Infinity,
    relativePoints: [ { x: 0.5, y: 0.2 } ], // instead of one elementOrigin object
    endOnly: true
  }
})
```

>I don't want any snapping behavior until the element reaches a drop zone, but I have no idea what changes I need to make.

You could calculate the positions of the dropzones on `down` or `dragstart` then create snap target objects with those coordinates and set an appropriate range then set the snap targets to be an array of those objects.

**Comment by HerrimanCoder** [comment]
taye, thanks so much for your thoughtful and detailed answer. Unfortunately what you suggested doesn't seem to work, and I'd like to show you side-by-side comparisons of what I have. First, this one works great:

(1)
http://instant-rsvp.com/temp/workscreen/ (drag a fuel tank from top left into the top-left zone and watch it elegantly snap down against the bottom of the zone, against the truck) -- this uses the deprecated method but works great.

Now this is the newer version of the API, non-depracated:
(2)
http://instant-rsvp.com/temp/workscreen2/ (doing the same drag/drop motion, but no snap occurs -- I have no idea what I'm doing wrong)

Ultimately I want the snap to work just like in #1, but using your newer/recommended approach, AND get snapping on the bottom zones working correctly. When you drag a fuel tank to one of the three "bottom zones" (under the truck instead of above it), I want the tank to slide and snap UPWARD against the truck, instead of downward.

How can this be done the right way? (I REALLY appreciate your time!)

**Comment by taye** [comment]
In your `dragenter` listener, you're still using the old API and trying to update the `anchors` array. You should change that to use the new API and update the `targets` array instead.

**Comment by HerrimanCoder** [comment]
taye, you nailed it. This is working great now, as far as the "above the truck" snaps. To get the snaps at the bottom of the truck to slide UP instead of DOWN, I believe you previously suggested this:

>> "You could calculate the positions of the dropzones on down or dragstart then create snap target objects with those coordinates and set an appropriate range then set the snap targets to be an array of those objects."

Do you know of a code sample that illustrates how to do this, or could you throw something together that gives me the general idea? I'm fuzzy on how to implement. Again, thanks very much.
