### ISSUE TITLE
How to make Interactible.fire(iEvent) work?

### ISSUE THREAD

**Issue by HerrimanCoder** [taye/interact.js#250]
My understanding of Interactible.fire(iEvent) is that I can automatically make a draggable element of my choice drop onto a dropzone of my choice. So I have a draggable image named `drag1`. And I have a dropzone named `drop1`. And I want to (on page load) cause drag1 to automatically go to drop1 dropzone. Note: I need drag1's initial position to be unchanged, as if the fire never happened, so that I can force it back to its initial start place in certain cases.

I am trying to call .fire() thusly:

```interact('#drag1').fire({
	type: 'drop',
	target: document.querySelector('#drop1')
	//target: 'drop1'
	//target: '#drop1'
});```

I positioned that chunk of code in various places in my code, including at the very end of all other js. But it does nothing. No errors get logged in Chrome dev tools, and just nothing happens.

Am I misunderstanding how to use this? Am I doing something wrong?

**Comment by taye** [comment]
>My understanding of Interactible.fire(iEvent) is that I can automatically make a draggable element of my choice drop onto a dropzone of my choice. 

That is not how it works. All it does is call the event listeners that were registered for the event's type. It doesn't start any interactions. It is used internally to call event listeners when actual user interactions are happening. You can't use it to force user interactions to happen.

If you insist on making interact.js think that actual user interactions are happening when they are not, then you can manually [create and trigger input events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) so that it looks like the user held the pointer down and moved to some other position and released the pointer. This is an overly complicated approach and I will not provide any further help on how you could do that. Read through the project's source code if you want to know what input events you would need to create.

**Comment by HerrimanCoder** [comment]
Solved here: https://github.com/taye/interact.js/issues/253
