### ISSUE TITLE
After inertia, 'gesturable' will be triggered even if one finger

### ISSUE THREAD

**Issue by faller** [taye/interact.js#317]
demo: http://jsfiddle.net/a19qzkzs/show
version: https://rawgit.com/taye/interact.js/unstable/dist/interact.js
environment: safari and chrome on ios9

**Comment by taye** [comment]
I'll try to test this as soon when I have access to an iThing.

**Comment by faller** [comment]
It's already fixed in the newest http://code.interactjs.io/v1.2.6/interact.js
thanks @taye

**Comment by faller** [comment]
I'm sorry it still doesn't work with unstable version https://github.com/taye/interact.js/blob/unstable/dist/interact.js

**Comment by voidmain26** [comment]
I have a very similar problem, but it doesn't involve gestures. I have 3 separate divs that are draggable and they all have inertia. While testing, if I quickly drag all three at the same time I can cause the browser/Interact(?) to miss the last "dragend" event. Basically, I throw one and it continues to slide, during the slide I throw two, and lastly throw three.  I keep a counter for "dragstart" and "dragend" and they don't match, "dragend" comes back one short. I have code that is dependent on the "dragend" and it doesn't run the final time.


If I had to guess, I think these two are related. I bet your final "gestureend" is never firing. Now, when you place a finger on the screen it thinks you already have pointers down.  Just to be clear, I'm using version 1.2.6 Stable, the version that Taye recommended above.

**Comment by voidmain26** [comment]
Here is a video of the above stated behavior happening on the interactjs.io page.

https://youtu.be/Mqd3_liIbK4

As you can see, simply dragging works fine, once I initiate an inertia event and then attempt to drag the other div things go wrong. The final "dragend" never seems to fire. You can see that I lose the ability to drag one div, but I can still drag the other. I assume this is because MaxPerElement defaults to 1 and there is already an interaction occurring on that element. Hopefully this help.s

**Comment by taye** [comment]
@voidmain26 Thanks! That was very helpful. I think I've fixed it on the [unstable](https://rawgit.com/taye/interact.js/unstable/dist/interact.js) version now.

**Comment by faller** [comment]
That works on the unstable version, thanks you guys.
