### ISSUE TITLE
Dragged element position and autoscroll

### ISSUE THREAD

**Issue by eGene** [taye/interact.js#353]
Browser: Chrome v 47.0.2526.111 m
OS: Windows 7

Issue is somewhat similar to https://github.com/taye/interact.js/issues/298, but proposed fix does not work as expected. Here is live demo: https://jsfiddle.net/beccvtzu/3/

1. drag #yes-drop element to the bottom edge of #outer-dropzone, make it scroll but keep #inner-dropzone visible; don't drop yet;
2. drag it back to top but don't let it scroll;
3. see how #inner-dropzone becomes droppable when dragged element is actually below it;

This makes it unusable when container is scrolled.

**Comment by Spittal** [comment]
I am having this exact same problem.

I've updated the fiddle to use a new version of Interact

https://jsfiddle.net/5wrLg56g/

A solution or workaround to this would be greatly appreciated

**Comment by Spittal** [comment]
@eGene 

I've dug through the code and I've found that they have a method that is not available in their API called "dynamicDrop" you can find it here:

https://github.com/taye/interact.js/blob/master/src/actions/drop.js#L18

I've found that if you set that flag to "true" this bug is no longer an issue. This property is not available in their API and I'm not sure if switching it to true breaks other parts of the library, but if you are looking for a quick fix. This is it.

**Comment by Spittal** [comment]
One last comment.

`dyanamicDrop` is actually part of the API now it's undocumented. You can enable this property very easily by using.

```javascript
interact.dynamicDrop(true);
```
