### ISSUE TITLE
Throttle mosemove and dragmove

### ISSUE THREAD

**Issue by salzhrani** [taye/interact.js#378]
I think it would be beneficial to throttle the `mousemove`, `dragmove` events listeners to once every 16ms.
##

**Comment by taye** [comment]
I'm not sure if it's a good idea to do this by default though. I can't think of many disadvantages or negative consequences of doing this but I'd like to be cautious and get some input from other developers.

**Comment by taye** [comment]
I'm closing this issue until some more opinions are expressed.

**Comment by Joeao** [comment]
I agree that doing this by default wouldn't necessarily be a good idea, though I can see the benefits in having it as an option.
In my use case I'm carrying out some pretty heavy actions onmove which don't necessarily need to occur each time the event is triggered. Instead of throttling I'm just setting an interval on the heavier tasks :

```javascript
var throttleInterval,
    moveTriggered = false;

interact(document.getElementById('wall')).draggable({
    onstart: function(e) {
        throttleInterval = setInterval(function() {
            if(moveTriggered) {
                heavyLoad();
                moveTriggered = false;
            }
        }, 50);
    },
    onmove: function(e) {
        moveThings();
        moveTriggered = true;
    },
    onend: function(e) {
        clearInterval(throttleInterval);
        moveTriggered = false;
    }
});
```

**Comment by CodeWithOz** [comment]
I think it will be best to not add default throttling because it's likely that different use-cases will require different throttling mechanisms. Developer should be able to decide how they want to throttle and implement accordingly. @taye  I do think a note should be added in the docs stating that these events are not throttled by default. I tried looking through the code and then eventually came to search the issues just to be sure. Better if it's stated upfront. Great work on the library :clap: !
