### ISSUE TITLE
interact throttles other events?

### ISSUE THREAD

**Issue by beckend** [taye/interact.js#382]
I am using the example of the front page, but with a clone appended to the body.

The clones moves around just fine and is very responsive, but there are mousemove events set on many elements on the page and their mousemove events are fired very slow compared to what they normally would fire when interact js is not active.

So I even tested to attach a mousemove event listener on the body/document, they fire at normal speed(fast) even when the clone is moving around, but any div below the document.body would lead to very slow mousemove event fire speed over my elements.

It's maybe even weird than slow, because if I drag the clone at "even slow pace" the mousemove is not even triggered even once! However dragging like a maniac, the mousemove events are fired "just fine".

But again, the mousemove events are fired normally at fast speed when the clone is not active.

**Comment by taye** [comment]
The mouse events don't get fired to the other elements because they're fired to the element that's under the cursor which will often be the element you're dragging unless you move far enough to go beyond the edge of the element that's being dragged. You can use [CSS `pointer: none`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) on the dragged element if you don't want it to receive pointer events.
