### ISSUE TITLE
what cause this error?

### ISSUE THREAD

**Issue by askie** [taye/interact.js#387]
when resize enabled, it's children element height will auto changed,
like this gif says: [gif](https://img.alicdn.com/imgextra/i2/20841398/TB2fJiNoFXXXXX7XFXXXXXXXXXX-20841398.gif)

I only want thange the resize element,
it's a bug or can been config?

thx!

**Comment by Joeao** [comment]
Hi Askie,

Welcome to the world of programming! Things can be a little crazy as you pick up languages and learn their quirks, but keep learning and soon you'll be a code master.
I see if you've found Github, a great place to share and contribute to open source code, as well as closed source. The issues section of Github is generally for reporting bugs, requesting features and sometimes sharing information and concepts to better help the projects future. It is not, however, for questions of how to work with the project, with exceptions, e.g. if the documentation is clearly lacking something important.

I recommend visiting great sites such as [Stack Overflow](stackoverflow.com) and [Gitter](https://gitter.im/taye/interact.js) in order to get your questions answered. These platforms allow you to ask all your questions without bothering the developer of the project. A person who has worked very hard to create this excellent piece of kit for us to build upon.

Now that I've guided you towards a better future of getting help on your problems, I can give some quick insight on your issue, despite this not being the right place.
Assuming that you're resizing the parent element of the image, rather than the image itself, you should try setting the height of the image as 100%, and the width as either 100% or auto. By setting the image height to 100%, it will react to the size of the parent, as you resize it. The height of the image responds to the width of the image if set to auto, and vice-versa. The image will skew if setting both to 100% and resizing the parent on one axis, so look out for that.

Have an excellent day, and make sure to leave similar questions outside of Github.

    - JoeAO
"there is no spoone" - The Matricks

**Comment by askie** [comment]
@Joeao thx!
I have read the API documents few times ,and does not find a solution,
so I have asked a question about this on stackoverflow,
[http://stackoverflow.com/questions/37150707/how-to-maintain-all-elements-independent-height-of-interactjs-removeable-elemen](http://stackoverflow.com/questions/37150707/how-to-maintain-all-elements-independent-height-of-interactjs-removeable-elemen)

**Comment by Jonzy3000** [comment]
@Joeao I think you've missed understood the problem. @askie wasn't asking about why his image is not re-sizing to fit the parent element, but in-fact why the other draggable elements change position when a re-size event occurs.
Perhaps a better example of this can be found [here](http://i.stack.imgur.com/TfGVj.gif)

[Relevant JSFiddle](https://jsfiddle.net/askie/660cgLpd/4/)
