### ISSUE TITLE
Div moves before stopping resizing

### ISSUE THREAD

**Issue by ludov-robert** [taye/interact.js#414]
First, thanks for your library !

I noticed a bug when resizing toward right or down (or both) : before stopping resizing (around 40px) the div moves.
You can see that on your demo on interactjs.io : if you resize from the top left corner, the div moves at the end before stopping when the text indicates 0. Maybe the size of the shape is not calculated well ?
Is there a way to lock that or should we wait for a new version ?
##

**Comment by taye** [comment]
I don't see it on the homepage. Can you record a video of it?

**Comment by ludov-robert** [comment]
Please find the video here : https://app.hyfy.io/v/ab7KxA4vUM/

When I resize the shape on your homepage, down to 40x40 it stops resizing and start moving.

**Comment by taye** [comment]
That's because resizing from the top-left changes the size **and** moves it at the same time but the element's `padding` style prevents it from actually being resized to 0x0 even if the `width` and `height` are set to `0px`. When the size becomes limited by the padding, the element is repositioned but isn't resized. You can use the recent [`resize.snapSize`](https://github.com/taye/interact.js/pull/455) setting to prevent this.
