### ISSUE TITLE
What do the branches mean? How are they related? Why are we advised to install unstable for fixes?

### ISSUE THREAD

**Issue by nruth** [taye/interact.js#417]
Is master a stable branch or a dev branch? What is unstable? 

I saw in other tickets that we should install the unstable branch to get bug-fixes for many problems being reported by bugsnag with touch-screen devices, but what does "unstable" mean in this project? Are any of the fixes in master?

I couldn't see any of this in the readme and it's a bit worrying installing something called unstable :)
##

**Comment by taye** [comment]
I do development on `master` and merge changes into the `unstable` where I build and commit the build files in the `dist/` directory. The documentation isn't ready for these changes which is why I don't commit to the `stable` branch wich is currently at `1.2.6`. I'm trying to get documentation, tests and a few bug fixes done before making a proper release.
