### ISSUE TITLE
interact.js cannot drag an object tag SVG

### ISSUE THREAD

**Issue by akinorikul** [taye/interact.js#424]
Hi,
I'm trying to move a svg object by drag/drop/scale and touch functionality. My SVG is enclosed in <object> tag which it seems to be not working fine with the interact.js :
<object class=draggable data="my_svg_url.svg" type="image/svg+xml"></object>
Is it possible to make it work ? 
##

**Comment by taye** [comment]
@akinorikul could you link to a codepen or jsfiddle demo that shows the error?

**Comment by akinorikul** [comment]
@taye here's a fiddle : https://jsfiddle.net/aLfy4hrL/1/
You'll see that the tiger (the svg object) is not draggable

**Comment by taye** [comment]
The problem is that the `<object>` element works like an `<iframe>` so the pointer events get sent to the page inside it. It works ff you change it to an `<img>`. If it must be an `<object>` then consider nesting it inside a `div.draggable` element and using a `<div>` to cover it. https://jsfiddle.net/aLfy4hrL/7/
