### ISSUE TITLE
Dragging doesn't working without "touch-action" css rule on mobile Chrome, Opera, etc.. Except mobile Firefox

### ISSUE THREAD

**Issue by believer-ufa** [taye/interact.js#564]
Hello! Please help me, describe what i doing wrong.

I created [simplest example](https://jsfiddle.net/2fqjywLc/) to test this library, but it doesn't work on mobile browsers except Firefox :(

### Expected behavior

Dragging working on all devices.

### Actual behavior

Dragging working only on desktop and on mobile Firefox. On mobile (or in chrome browser with mobile emulation) dragging will start, but ends just after few moves.

### System configuration
**interact.js version**: 1.3.1
**Browser name and version**: Chrome, Opera, etc?..
**Operating System**: Android, Arch linux, etc?..

**Comment by believer-ufa** [comment]
Ow, i finded solution! See [working example](https://jsfiddle.net/tdt6Ldbm/1/).

Can you add node about it on your website?

**Comment by greyseer256** [comment]
I'd like to upvote this issue. I encountered the same problem while upgrading from `1.2.9` to `1.3.3`. When dragging the `dragend` event fires almost immediately after `dragstart`. I was able to reproduce this behavior in mobile emulator mode on Chrome 63 and in Chrome 63 on a Samsung Galaxy S6 . It works fine for desktop.

This change was introduced sometime between `1.3.0-alpha.3` and `1.3.0-alpha.5` (`alpha.4` is not available on NPM). 

[JSFiddle reproducer](https://jsfiddle.net/L3twvvzx/)

Thanks for the workaround @believer-ufa!

**Comment by taye** [comment]
Closing this and leaving #595 open.

**Comment by mxdmedia** [comment]
Any updates on this issue?  It definitely makes things a bit difficult when trying to use interactjs on an iOS device.  I also found that this issue is present when resizing as well.

I did come up with a (somewhat janky) workaround that seems to fix the issue on both iOS and Android- add an event listener for the various touch events, that fire `event.preventDefault()` and append this to the element using the `on<event>start` callback and remove them from the element using the `on<event>end` callback.  For example:

```javascript
function ignoreTouch(e) {
  e.preventDefault();
}

// Later in the code

interact(ele).resizable({
  edges: { left: false, right: true, bottom: false, top: false },
})
.on('resizestart', (evt: any) => {
  // nullify touch events.
  ['touchstart', 'touchmove', 'touchend'].forEach((et) => ele.addEventListener(et, ignoreTouch));
})
.on('resizemove', function (event: any) {
  // do stuff while resizing the element
})
.on('resizeend', (evt: any) => {
  // Remove nullify touch events in case we need to use touch events for something else.
  ['touchstart', 'touchmove', 'touchend'].forEach((et) => ele.removeEventListener(et, ignoreTouch));
  // Code to handle the resized element when resizing is complete.
});
```

Note that you must use a named function (in my case `ignoreTouch`), if you want to remove those event listeners when you are finished resizing/dragging.
