### ISSUE TITLE
Type definitions are not up-to-date

### ISSUE THREAD

**Issue by ItaHeld90** [taye/interact.js#572]
Hey,
the software I'm working on is using typescript and we are trying to integrate interact.js into our code.
I've noticed that you have a 'd.ts' file, but it's not up-to-date and some definitions are missing (Interactable.unset for example).

Please let me know if it is still maintained, and if any updates are expected soon :)

**Comment by taye** [comment]
The index.d.ts file was added by @lddubeau. I don't want to update the file myself, but I'd be happy to accept pull requests :).

**Comment by lddubeau** [comment]
The surface information provided by Github when looking at the history of `index.d.ts` is misleading. I actually renamed `interact.d.ts` to `index.d.ts` to fix a problem whereby the TypeScript compiler could not find the typings without additional (and unnecessary) configuration, and made some changes to the content of `index.d.ts` to fix other problems. There's a [commit](https://github.com/taye/interact.js/pull/539/commits/013ba1d6704686ad3401c49c684241b09e4b398d) showing the rename operation.

Since the `interact.d.ts` file pre-existed my involvement, I inferred there was an "official" decision to provide TypeScript typings with interact.js, but now I'm wondering whether the typings were included without considering the implication it has for maintenance.

The implication is this: whenever the public API of interact.js changes, the TS typings have to be updated to reflect the change, in the same way that the documentation must be updated when the public API changes. Ideally, someone who uses interact.js to its fullest and is up-to-date with the latest development would be responsible to make the update before a version with public API changes is released. And this person has to be versed with TS. Unfortunately, I'm not this person: I am versed with TS, but I use only a small part of interact.js, and I'm a few versions behind.
