### ISSUE TITLE
pointerEvents can not be disabled

### ISSUE THREAD

**Issue by DrSensor** [taye/interact.js#577]
### Expected behavior
`pointerEvents` can be disabled

### Actual behavior
neither `.pointerEvents(false)` or `.pointerEvents({ enabled: false })` works

### System configuration
**interact.js version**: 1.3.2
**Browser name and version**: Google Chrome Version 63.0.3239.108 (Official Build) (64-bit)
**Operating System**: ubuntu 16.04 LTS

**Comment by artaommahe** [comment]
@taye looks like same issue - after calling
```
      .draggable(false)
      .resizable(false)
      .unset()
```
interact lib still listening to `pointermove` event and it's huge slowdown for SPA and slow PC/IE11. Dunno how to remove this listener

**Comment by artaommahe** [comment]
@taye  Ok, after some debugging i found that i need to call manually
```
interact(document)
  .unset();
```
But this will not work due to this typo on this line
https://github.com/taye/interact.js/blob/master/src/utils/events.js#L88
when we're adding listener there is no `on` prefix
https://github.com/taye/interact.js/blob/master/src/utils/events.js#L53
After removing this prefix everything works fine.
So there is 2 problems
- wrong event listeners removing
- no document listeners cleanup (mb lib should check that there is no other interact instances and cleanup this listeners)

**Comment by taye** [comment]
I don't think it's a good idea to add such an option. I think it's better to remove each pointerEvent listener with `interactable.off(type, func)`.
