### ISSUE TITLE
draggable blocks click

### ISSUE THREAD

**Issue by jdewit** [taye/interact.js#58]
A link inside a draggable element does not fire a click event when clicked.

checkout <a href="http://plnkr.co/edit/wd0KZv?p=preview">plunkr</a> and click the link in the item.

Only seems to happen on touch devices. (ipad3 android).

**Comment by markadrake** [comment]
Hi Taye, I have a project where I can't seem to get the click event to fire properly. I can't post the source code at the moment because it isn't clean and to the point - but ultimately I have an un-ordered list element with images inside. The images have interact draggable assigned to them. The images also need to respond to the click event. But on mobile devices, the click event is ignored. Not globally - but only for elements that are draggable.

So I attempted solution number 2, and replaced the click event with interact's tap event. However, now desktop is messed up. On the tap (or click) event I toggle an info window's visibility. I also register a one time document click event so that the info window will be toggled off if the user interacts with anything else on the page. Now, on desktop, this event seems to fire off immediately. It's as if the "tap" event triggers a "click" event directly after running, even though I have e.preventDefault() and e.stopPropagation(). It's the damnedest thing. 

Any thoughts on what I might be fighting with?

Do you think attaching the draggable event to the <li> and leaving the click event on the <img> would straighten things out?

**Comment by taye** [comment]
Hello!

>The images also need to respond to the click event. But on mobile devices, the click event is ignored.

Because the images are draggable, interact.js calls `preventDefault` on the `touchstart` and `touchend` events on the mobile device. Browsers fire MouseEvents by default after TouchEvents and these simulated events can be prevented (at least on Webkit/Blink; I don't think it works on Firefox) by calling `preventDefault` on the TouchEvents and that also prevents the simulated click event.

>Now, on desktop, this event seems to fire off immediately. It's as if the "tap" event triggers a "click" event directly after running, even though I have e.preventDefault() and e.stopPropagation(). It's the damnedest thing.

Click events can't be prevented by calling `preventDefault` or `stop[Immediate]Propagation` on the preceding mousedown and mouseup events. The only thing you can do is to stop the click event's propagation early on as I explained here: https://github.com/taye/interact.js/issues/217

```javascript
interact(target).on('click', function (event) {
  event.stopImmediatePropagation();
}, true /* useCapture */);
```

**Comment by crawld** [comment]
thanks @seltix5 your solution helped me. i had to modify it slightly (closest() returns an array), but now <a href> works in draggable components.

**Comment by shubh3695** [comment]
Is there any permanent solution to this issue? The solution mentioned above stopped working after upgrading to v1.4.0

**Comment by tryhardest** [comment]
+1 @shubh3695 how did you figure it?

**Comment by shubh3695** [comment]
Given that this issue was mostly on iOS, @tryhardest I had to capture "tap" events on the mobile device [detected by navigator], and then "click" the Element manually. it was a work-around, not a solution.

**Comment by taye** [comment]
I'm closing this issue in favour of https://github.com/taye/interact.js/issues/859.
