### ISSUE TITLE
Center Position Draggable Element to Cursor On Drag Event

### ISSUE THREAD

**Issue by pegues** [taye/interact.js#582]
I'm having a little trouble with my implementation of interact.js for the draggable element. How do I force the center of the draggable item to be positioned at the center of the cursor once the drag event for the draggable element is initiated.? I don't know how to proceed with doing this. I searched as much as I could, and found topics about axis and snap, but none of these relate to centering the draggable element to the cursor.

I'm using the following for making an element draggable:

`interact('.draggable').draggable({...});`

The draggable item is width: 19px and height: 32px, and is always positioned in the bottom right-hand corner of the screen until grabbed and dragged.

Once the drag event is released, I reset the position of the draggable element.

**Comment by mrtwebdesign** [comment]
Base on how draggable usually works, you may have to do that yourself before it's "draggable". Detect the click and hold, set the element position under the mouse pointer, then make it draggable and let interact.js take over.

interact.js stores the x/y position with data-x and data-y and sets it with inline css(transform translate), so you can keep that position even if you remove it as a draggable element from interact.js. Knowing the container width and height in px then doing your own math, you can calculate a new position and update the x/y and css position so it's ready when handing it back to interactjs. I have to do something like that to store the position for all my draggable elements on the server.

I'm not sure about the handoff on that last step. That would require making it an active draggable element by code rather than mouse selection, but you may have to experiment with it.

Normally I see drag actions where the drag starts out at the current position when clicked-on and only moves as much as you move the mouse until you let go. After that it stops or you have inertia on and it keeps going until it hits something or runs out of 'inertia'.

Having it jump to being centered when selected sound like a UX choice that may surprise the user and feel awkward. Do you have any existing examples of it being implemented in that manor?

**Comment by pegues** [comment]
Here is a very old example of what I'm doing. The mouse down event and the animation is still the same in this example though with my current project state: http://jsfiddle.net/pegues/a5mn1ogu/

The position of the mouse cursor is not a huge difference (between 5 to 15 pixels top to bottom grab region), but this difference can be a difference of 5 to 10 meters in GIS. Because of the difference in mouse grab within the 'bottom right container', centering the 'draggable' with the mouse cursor would provide for more accuracy.

In the example, the moment you mouse into the container from the top, grab and move - observe the position of the mouse cursor to the 'draggable' element. Then repeat the behavior from the bottom, and the moment the drag handle becomes available, drag again. observe again the difference in positioning of the 'draggable' vs the mouse cursor.
