### ISSUE TITLE
'hold' event not working reliably on android/chrome

### ISSUE THREAD

**Issue by Ladret** [taye/interact.js#602]
Ive put together a codepen that should test the 'hold' event, pretty much the same as on the demo page, see: https://codepen.io/anon/pen/LQbOpx

_(Please note that this is only reproducible on an android device using chrome.)_ 

### Expected behavior
Long pressing an element should trigger 'hold' event every time

### Actual behavior
Long pressing triggers hold occasionally, the longer the hold duration, the harder it gets to 'hold'

### System configuration

**interact.js version**: 1.3.3
**Browser name and version**: Chome 64
**Operating System**: Android 7.0 (Running on Samsung Galaxy Tab S2)

This works fine in Firefox on the same device, and it works without problems on iphone and ipad as well.

**Comment by Ladret** [comment]
Found the issue and solution:

Increasing the pointerMoveTolerance to 5 makes evertying work fine on android too.

interact.pointerMoveTolerance(5);

**Comment by taye** [comment]
Thanks for reporting this problem. I'm going to reopen this as a few people have mentioned similar issues with high DPI phones. If I get one eventually I'll look further into a reliable solution.

**Comment by jtara** [comment]
I'd like to request that it be possible to set *pointerMoveTolerance* independently for each interactable. Currently, it is a global option, right?

That way, it could be set to a larger value for simple interactions on buttons, and decreased for gestures. 

That way, the only time it would really be an issue would be if you are looking for both tap (or hold) and moving gestures on the same node(s).

I am using interactJS for ALL interactions in a hybrid mobile app. (WKWebView on iOS, WebView on Android.) We've had a terrible time with buttons on Android. Curiously, no problem on iOS. (I know that iOS still doesn't have *pointerEvents* yet, though.)

In the mean time, really, if you are going to set *pointerMoveTolerance* it should be set based on device PPI and device pixel ratio, if known. Since I am developing for a hybrid mobile platform, I do have PPI and DPR easily available.

That is, one should normalize for this. That said, it's typically not a HUGE range.

It ranges from e.g. .038" on a Galaxy Tab S2 to .046" on an iPhone X. Either of those, really, seems a tad small.

I am adding code right now to my project to normalize it, and will try 0.1" for starters.

**Comment by jtara** [comment]
FWIW, I wound-up using 1px *pointerMoveTolerance* on iOS WKWebview, and calculated value on Android WebView based on a value of 0.05". So, e.g. 0.05 * ppi / device-pixel-ratio.

I had been using 5 px, but button response was horrible - any slightly glancing blow would cause tap to not be recognized.

Maybe there are fundamental differences in iOS vs typical Android hardware that contribute to this?

When I use a stylus, (or Genymotion simulator with mouse)  I have no trouble on Android. But tap is unreliable at 5px, and unusable at 1px on Android.

This is with 1.34, BTW.

**Comment by taye** [comment]
Whoops. Closed the wrong issue.

**Comment by taye** [comment]
Haven't found a solution for this, but I'm going to close this issue as there's no certain way to get the device PPI in the browser and using a `pointerTolerance` value of around 5 should work.
