### ISSUE TITLE
DropEvent not exported with other event from @interactjs/types

### ISSUE THREAD

**Issue by nayfin** [taye/interact.js#825]
### Expected behavior
To be able to: 
`import { DropEvent } from '@interactjs/types/index';`

### Actual behavior

I have to do this:
`import { DropEvent }  from '@interactjs/actions/drop/DropEvent'`
and install:
`@interactjs/actions` 
or else I get a compilation error in my Angular app.
`ERROR in The target entry-point "@tft/interact" has missing dependencies: - @interactjs/actions/drop/DropEvent`
### System configuration
**interact.js version**: 1.9.18
**Browser name and version**: chrome latest
**Operating System**: Windows
### Additional Info

I have wrapped your library in an angular wrapper. Right now consumers of the library have to install `interactjs` and `@interactjs/actions` or else they will get error: 

`ERROR in The target entry-point "@tft/interact" has missing dependencies: - @interactjs/actions/drop/DropEvent`

Is there a preferred way to import types from interact? It seems like the import paths have changed a few time recently.

**Comment by taye** [comment]
Sorry about the frequency of changes. I've been trying to get a setup that's easy to develop and consume. Ideally, I'd like to have:

 1. types defined in their respective modules for better organisation
 2. a single namespace which contains common types that are used during the development of the library in order to reduce the amount of imports 
 3. a global `Interact` namespace that can be used by library consumers to access exposed types without having to import them
 4. a single, dependency-free package containing all exposed type definitions

It took a while, but I've gotten all of those except _number 2_—I can't use the global namespace from _number 3_ internally as that [doesn't get compiled as expected](https://github.com/taye/interact.js/commit/81ef735a967204be455cc08fae3ca8b742fa1023#diff-8103a5b31411bef6debeae094602241e), so I now `import * as Interact from '@types/interactjs/index'` [whenever it's needed](https://github.com/taye/interact.js/commit/86022034502e4c15c93003100a029210d70eff60).

The easiest way to use the types is from the global `Interact` namespace. I don't intend to remove types from that namespace unless the related behaviour has been removed after deprecation, or it's not used in any of the documented methods.

I'll soon publish a version that exposes `Interact.DropEvent` and if you have any other suggestions, I'll take a look for those too.

**Comment by nayfin** [comment]
@taye No apologies necessary, breaking changes are expected when using a library developed by a one-man-army 😃. I too am struggling with organizing my typescript exports in a way that is as convenient for the consuming developer as it is for me. 

What benefit is there to exposing the the global `Interact` variable over exporting all types from an package entry point in `interactjs`?

 I don't mean to throw another factor into an already confusing issue, but I recently watched a talk about how you can export all the things in a tree-shakable way, so the end-developer only bundles what they use. This was at our local Angular meetup, and it usually takes a couple weeks before the talks are published to YouTube, but once they are I can post the link here. I think it would be super helpful for what you are trying to do. 

Also, I'd love to start contributing to this project. So if you'd like me to commit a PR to expose the the `DropEvent` just let me know and I will get at it. Would you mind if I export from the `types` directory as well so that I can keep my code consistent?

Thanks again for working so hard to give the world a great free drag and drop library!

**Comment by taye** [comment]
>What benefit is there to exposing the the global Interact variable over exporting all types from an package entry point in interactjs?

Before I rewrote things in typescript, someone contributed an `index.d.ts` file which exposed a global `Interact` namespace, and I wanted to keep that the same to avoid some hassle for consumers. I also kind of like having a namespace with all the types that you need without having to import it. I don't mind changing that though.

One thing that might be annoying to deal with would be having to import and then re-export the types from the `@interactjs/types` package. The `interactjs` package is now just a bundled version of `@interactjs/interactjs` which imports all the plugins under [`/packages/@interactjs`](https://github.com/taye/interact.js/tree/master/packages/%40interactjs) and then exposes the `interact` function from `@interactjs/interact`. I'm not sure if there's a good way to make the `interactjs` package export both the `interact` function and all the types, or if that's even a good idea. I'd be happy to hear more ideas :D.

>I don't mean to throw another factor into an already confusing issue, but I recently watched a talk about how you can export all the things in a tree-shakable way, so the end-developer only bundles what they use.

I've fairly recently started working on this. You can find some of the progress in issue #800.

>This was at our local Angular meetup, and it usually takes a couple weeks before the talks are published to YouTube, but once they are I can post the link here. I think it would be super helpful for what you are trying to do.

I'd like to see this talk :slightly_smiling_face:.

>Also, I'd love to start contributing to this project. So if you'd like me to commit a PR to expose the the DropEvent just let me know and I will get at it.

It was pretty quick to fix, so I just did it and published `v1.9.19` while writing this response.

I'll be honest, I'm not used to having frequent contributors at all :sweat_smile:, but I'd like to change that. I don't think the dev setup works for windows and mac and there's no contributor readme so it might be a pain to get set up, but please try if something comes up again that you'd like to fix.

**Comment by nayfin** [comment]
@taye it seems like interact has gotten more tree-shakeable! I just published my angular wrapper library (the only changes being to upgrade interact and angular) and my unpackaged size went from 816kb to 536kb! Thanks for the free file shrinking!!!

**Comment by taye** [comment]
Neat :D

**Comment by nayfin** [comment]
[Here's](https://www.youtube.com/watch?v=eTGbGv2VxSU) that video I mentioned early about helping typescript tree shake unused code.
