### ISSUE TITLE
Double tap breaks on iOS 13.5

### ISSUE THREAD

**Issue by szilardszaloki** [taye/interact.js#828]
Hi there,
Double tap breaks on iOS 13.5 (Safari, Chrome, Firefox, Opera) with HTML5 canvas element. Out of curiosity, I checked with Edge for iOS as well and surprisingly it works.

**Comment by taye** [comment]
Can you try calling `interact.pointerMoveTolerance(5)` to see if that makes any difference?

**Comment by szilardszaloki** [comment]
I've just checked it, it doesn't help.
It looks like all touch events are broken in general by the way. Even `touchstart`'s event handler doesn't get called the second time when a double tap occurs (the default double tap zoom is triggered though). I might move on to other gestures temporarily, as long as Apple fixes their broken iOS release.

**Comment by szilardszaloki** [comment]
Hi @taye,
In case you're about to fix it: calling `preventDefault()` on the touch event itself solves the issue.

**Comment by timothyallan** [comment]
I'm starting to get client reports trickling in saying that click functionality sometimes freezes on 13.5.1. It's happened to me as well a few times, but I can't get a reproducible case yet!

**Comment by AlwaysAwake** [comment]
@szilardszaloki 
Isn't it related to Webkit bug?
I found some issues that might be related to this "Skipping Second Touch" behavior in Webkit Bug Tracker.

* https://bugs.webkit.org/show_bug.cgi?id=211521
* https://bugs.webkit.org/show_bug.cgi?id=203786
* https://bugs.webkit.org/show_bug.cgi?id=211179

![ezgif com-optimize](https://user-images.githubusercontent.com/7885963/91015753-a6372900-e626-11ea-9085-1cba86f2832f.gif)

This bug seems to be starting from iOS 13.4.1 and It's still happening even in 13.6.1
[Please see repro here.](https://codepen.io/alwaysawake/pen/MWKYPdW)
