### ISSUE TITLE
allowFrom doesn't work when manualStart is on

### ISSUE THREAD

**Issue by ddenev** [taye/interact.js#845]
https://jsfiddle.net/ddenev/fvzy6mjh/

What is the proper way to specify a handle when `manualStart` is on then?

@taye , please don't ignore this and the 'cursorChecker' (https://github.com/taye/interact.js/issues/844) questions - I am currently blocked and need assistance/resolution.

Thank you and best regards.

**Comment by taye** [comment]
Undocumented, but you can use `interactable.testIgnoreAllow(...)`.

https://github.com/taye/interact.js/blob/cd172e40512ec5d4c7946bd1f498724519ee63b5/packages/%40interactjs/core/Interactable.ts#L232-L240

**Comment by ddenev** [comment]
Thanks but not sure how do I use that function... It returns a boolean so what do I do with that value in order to make my `allowFrom='selector'` work?

**Comment by ddenev** [comment]
Thanks but not sure how do I use that function... It returns a boolean so what do I do with that value in order to make my `allowFrom='selector'` work?

**Comment by ddenev** [comment]
+1

**Comment by taye** [comment]
The proper way is to check yourself if you want to start the action from the target element. You can use that `interactable.testIgnoreAllow()` method to check if the `allowFrom` and `ignoeFrom` options that you set should allow the action (`true`) or not (`false`) before calling `interaction.start()`

**Comment by nayfin** [comment]
@ddenev I moved my clone logic into the `dragstart` event and removed the `manualStart` and `interaction.start({..})` stuff. This has the advantage of preserving my drag config (allowFrom, cursor, etc...). The disadvantage that my clone isn't associated as the `event.target` for drag events or the `event.relatedTarget` for drop events, these properties are associated to the original drag item (the trigger if you will). I'm assuming this the reason @taye made the `manualStart` functionality, so that you could associate the clone as your drag item. I get around this by adding the properties I need to the element that is being dragged and reference those properties instead of `target` and `relatedTarget`.  #shamelessPlug Additionally, I'm adding this functionality to an Angular drag drop library I have published `@tft/interact`. Interactive docs [here](https://stackblitz.com/github/nayfin/tft-documentation). I should be able to release the new feature and update docs with example by tonight or tomorrow.
