### ISSUE TITLE
Long-running pointer events even without registering listeners

### ISSUE THREAD

**Issue by CodeWithOz** [taye/interact.js#868]
### Expected behavior
There shouldn't be such long running interactjs handlers for events that I haven't even registered handlers.

### Actual behavior
I get long-running interactjs event handlers for events that I haven't registered interactjs handlers on, particularly pointer events. Have a look at this screenshot:
![szoter_annotated_image (2)](https://user-images.githubusercontent.com/28525986/98438767-b1a9d480-20ec-11eb-9c97-e6577f73b007.jpeg)

I would expect that interactjs isn't listening to events when I have not registered them. Is there a way to prevent this?

### System configuration
**interact.js version**: 1.9.22
**Browser name and version**: Chrome Webview 85
**Operating System**: Android 8

**Comment by taye** [comment]
Those listeners are added after the first interactable is created and are used for action auto-start (`manualStart: false`).

I'm very sure that those tasks take so long only because of overhead caused by chrome's dev tools. You'll get a similar result even if you profile an empty page running just `setInterval(() => {}, 50)`.

![immagine](https://user-images.githubusercontent.com/1679746/100396923-81988600-3047-11eb-87e7-45bbddf298e4.png)

You don't have to worry about this.

Related: #840
