### ISSUE TITLE
Dropzone not working inside a web component / lit-element

### ISSUE THREAD

**Issue by gero1992** [taye/interact.js#915]
Hi, I'm new to interact js, but I would like to say thank you for the great library :)!

I'm trying to use the dropzone feature inside my web component, which is implemented with lit-element, but without success.
I basically copy-pasted the demo from the website. 
See demo here: https://codepen.io/gero1992/pen/bGqpJbP

### Expected behavior
The demo works the same as in the website with enabled drop zones.

### Actual behavior
Only the dragable feature works. The dropzone events are not triggered.

### System configuration
**interact.js version**: 1.10.11

### Browser name and version:
**Operating System**: Windows 10
**Browser**: Google Chrome
**Version**: 90.0.4430.212

**Comment by gero1992** [comment]
Adding a comment to keep it active

**Comment by LukeTOBrien** [comment]
I have used Lit Element to create a drappable component, in my case I set the [renderRoot](https://lit-element.polymer-project.org/guide/templates#renderroot).  
I think the issue is with getting a reference to the element `interact(".dropzone")` - The element `.dropzone` is inside the shadowroot not inside the document.

Try and see if it works,
