### ISSUE TITLE
interact in an iFrame

### ISSUE THREAD

**Issue by alexiskattan** [taye/interact.js#97]
First off, I absolutley love this library.  It is really well done and I find it really useful.

I can get interact to work fine under normal conditions.  Now, I'm trying to activate interact from a parent frame.  Here is the code:

```
$("#my_iFrame")[0].contentWindow.interact('.draggable').draggable({
    onmove: function (event) {
        var target = event.target, x = (parseFloat(target.getAttribute('data-x')) || 0) + event.dx, y = (parseFloat(target.getAttribute('data-y')) || 0) + event.dy;
        target.style.webkitTransform = target.style.transform = 'translate(' + x + 'px, ' + y + 'px)';
        target.setAttribute('data-x', x);
        target.setAttribute('data-y', y);
    }
})
```

I'm really stumped as to what could be causing the issue.  If you have any ideas, let me know!

**Comment by 73rhodes** [comment]
Great library! It seems like cross-frame dropzones almost work, but the coordinates are off, especially when the iframe is scrolled. Any plans to revisit this one?

**Comment by taye** [comment]
@73rhodes Yes, but I doubt that I'll be able to do it in within the next two months. It will have to be after #231 is merged.

**Comment by taye** [comment]
Because interact.js no longer calls `preventDefault` on `mousedown` events by default, the offset coordinates doesn't happen if you start dragging in a child frame and move outside the frame's borders and over it's parents. The problem still exists on Firefox when you move from a parent over a child frame. A fix for that would be to cover the child iframe with a transparent element.

I'm closing this issue and leaving [#77 - "Drag & Drop between frames"](https://github.com/taye/interact.js/issues/77) open.
